openapi: "3.0.0"
info:
  version: 1.0.0
  title: TODO
servers:
  - url: http://localhost/
paths:
  /:
    post:
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/item'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
  /{id}:
    get:
      operationId: get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/item'
components:
  schemas:
    item:
      type: object
      properties:
        property1:
          type: string
        property2:
          type: object
          properties:
            property21:
              type: string
            property22:
              type: string
        decimalProperty:
          type: number
